### ISSUE TITLE
Vue Vault: Type error Object is not a function

### ISSUE THREAD

**Issue by thim81** [apideck-libraries/vue-vault#1]
### Description

There are some errors (see image attached). I’m using the sample code from the NPM registry.

> yarn --version
1.22.18
> node --version
v14.20.0

![image](https://user-images.githubusercontent.com/952446/210210150-945e6789-e488-44cb-ab4a-bebb1c208353.png)

### Context
https://apideck-io.slack.com/archives/C049WKXR4EB/p1672648388772439

**Comment by elsmr** [comment]
This is related to Vue 2. vue-vault only supports Vue 3+ at the moment.
